### ISSUE TITLE
Problem on xammp and windows server

### ISSUE THREAD

**Issue by nanoziobelo** [cwacha/iaddressbook#11]
Hi 
I copy file in folder and make installation step but when finish give error on redirect
http://localhost/Rubrica/index.php/home and page not view

**Comment by cwacha** [comment]
Hi

This is a known bug. Please ensure the install folder (Rubrica) is all
lowercase. Then it will work.

Cheers
Clemens

nanoziobelo ***@***.***> schrieb am Sa. 10. Apr. 2021 um
12:11:

**Comment by cwacha** [comment]
Duplicate of #10
