### ISSUE TITLE
Problem in get_magic_quotes_gpc()

### ISSUE THREAD

**Issue by janasco** [cwacha/iaddressbook#5]
There's a problem in your http://demo.iaddressbook.org/
Many errors is showing.
Kindly update as soon as possible.

**Comment by zenjubbers** [comment]
Seeing the same on the application running on Fedora32. These are the warnings showing on the main login page after a recent system update.

Deprecated: Function get_magic_quotes_gpc() is deprecated in /home/www/iaddressbook-4.0.0/lib/php/init.php on line 29

Deprecated: Function get_magic_quotes_runtime() is deprecated in /home/www/iaddressbook-4.0.0/lib/php/init.php on line 37

**Comment by cwacha** [comment]
fixed in master
