### ISSUE TITLE
Error in Firefox

### ISSUE THREAD

**Issue by Rid-lin** [cwacha/iaddressbook#6]
jQuery.Deferred exception: $(...).offset() is undefined @http://192.168.65.155/iaddressbook/:287:52
l@http://192.168.65.155/iaddressbook/lib/tpl/default/js/jquery-3.3.1.min.js:2:29375
a/</c<@http://192.168.65.155/iaddressbook/lib/tpl/default/js/jquery-3.3.1.min.js:2:29677
 undefined jquery-3.3.1.min.js:2:30930
TypeError: $(...).offset() is undefinediaddressbook:287:52
    <анонимный> http://192.168.65.155/iaddressbook/:287
    jQuery 2
        l
        c

**Comment by Rid-lin** [comment]
Hello, I got an error in the Java Script console.
Please tell me how I can fix this.

**Comment by cwacha** [comment]
I don't get this error neither in Firefox 72 nor in Safari 13.1.1. Sorry, I cannot reproduce this problem.

**Comment by Rid-lin** [comment]
Thanks for the answer.
Very strange. I have firefox 77.0.1 and this error is reproduced on it. (I assume that the error is in it).
But in the Vivaldi (Chrome) browser, everything works fine.
